name: nanodart
description: Tools for the NANO and BANANO cryptocurrencies including key
  generation, signing, encryption, and more.
version: 1.0.0
homepage: https://github.com/appditto/nanodart
author: Appditto LLC <hello@appditto.com>

environment:
  sdk: '>=2.5.0-dev.2.1 <3.0.0'

dependencies:
  pointycastle: ^3.0.0-nullsafety.2
  hex: ^0.2.0
  convert: ^3.0.0
  fixnum: ^1.0.0
  bip39: ^1.0.6

dev_dependencies:
  test: ^1.16.8
